name: Build

on:
  workflow_dispatch:

jobs:
  buildttf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install afdko
      run: pip3 install afdko
    - name: Install wine
      run: sudo apt update && sudo apt install wine
    - name: Begin
      run: python3 ./build/buildttf.py

    - uses: actions/upload-artifact@v3
      with:
        name: AdvocateAncientTTFs
        path: "*.7z"

    - name: Upload to release
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "test-01"
        artifacts: "*.7z"
        allowUpdates: true
        prerelease: true
        draft: true
        name: "Build Test"
        body: "Advocate Ancient"

  buildvf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install afdko
      run: pip3 install afdko
    - name: Begin
      run: python3 ./build/buildvf.py

    - uses: actions/upload-artifact@v3
      with:
        name: AdvocateAncientVFs
        path: "*.7z"

    - name: Upload to release
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "test-01"
        artifacts: "*.7z"
        allowUpdates: true
        prerelease: true
        draft: true
        name: "Build Test"
        body: "Advocate Ancient"

